### ISSUE TITLE
3dcitydb importer exporter

### ISSUE THREAD

**Issue by nurulaysyah** [tum-gis/3dcitydb-importer-exporter-docker#3]
hi 
i want to import xml file into 3d database using 3dcitydb importer exporter but now i am facing a problem with texture coordinate during importing process. can i know what the cause of this error and what is the solution can be make to overcome this problem

![error texture skp2 centipede](https://user-images.githubusercontent.com/88415784/128119387-2df559b2-ff7e-4bb9-9fac-8d8cb07d624c.PNG)

**Comment by BWibo** [comment]
Hey there, 
closing, as this is an issue of the [ImporterExporter](https://github.com/3dcitydb/importer-exporter) application and not the Docker image. Please repost your issue there.

Moreover, we will need more information to help you, especially an example dataset would be very helpful.
The screenshot you provided is barely readable but from what I can recognize, it seems that the XML structure of the file you are trying to import is messed up for TextureCoordinates.
Compare the structure in you file with a valid file or the [CityGML standard](https://www.ogc.org/standards/citygml). 
Check this section of the standard document for an examlpe:
*G.8 Example of a CityGML dataset illustrating the use of texture coordinates for complex surfaces with holes*

If you created the dataset with external software (like FME), it is likely that there is something wrong with the process regarding textures in that software.

**Comment by thomashkolbe** [comment]
Hallo Bruno,

ich hatte bereits vor einigen Tagen auf diesen Issue 
geantwortet, allerdings per EMail. Ich bin bisher immer
davon ausgegangen, dass Github dann die Antwort auch
im Repository verzeichnet, was aber offenbar eine 
falsche Annahme war...

Deswegen hatte ich letztens auf den anderen Issue, den+
Du beantwortet hast noch den Inhalt meiner EMail, die
ich ebenfalls vor einigen Tagen geschrieben hatte, 
hineinkopiert.

Viele Grüße
Thomas 

---------------------------------------------------
Prof. Dr. Thomas H. Kolbe  -  Chair of Geoinformatics
Dept. of Aerospace and Geodesy, and
Dept. of Civil, Geo and Environmental Engineering
Technische Universität München
Arcisstr. 21, 80333 München, Germany
Tel.: +49 89 28923888  WWW: https://lrg.tum.de/gis/
